/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EntryType = IDL.Variant({
  'expense' : IDL.Null,
  'saving' : IDL.Null,
  'income' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FinanceEntry = IDL.Record({
  'id' : IDL.Text,
  'entryType' : EntryType,
  'owner' : IDL.Principal,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFinanceEntry' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Int, IDL.Text, EntryType, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFinanceEntry' : IDL.Func([IDL.Text], [], []),
  'getAllFinanceEntries' : IDL.Func([], [IDL.Vec(FinanceEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntriesByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(FinanceEntry)],
      ['query'],
    ),
  'getEntriesByType' : IDL.Func(
      [EntryType],
      [IDL.Vec(FinanceEntry)],
      ['query'],
    ),
  'getFinanceEntry' : IDL.Func([IDL.Text], [FinanceEntry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFinanceEntry' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Int, IDL.Text, EntryType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EntryType = IDL.Variant({
    'expense' : IDL.Null,
    'saving' : IDL.Null,
    'income' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FinanceEntry = IDL.Record({
    'id' : IDL.Text,
    'entryType' : EntryType,
    'owner' : IDL.Principal,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFinanceEntry' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Int, IDL.Text, EntryType, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFinanceEntry' : IDL.Func([IDL.Text], [], []),
    'getAllFinanceEntries' : IDL.Func([], [IDL.Vec(FinanceEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntriesByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(FinanceEntry)],
        ['query'],
      ),
    'getEntriesByType' : IDL.Func(
        [EntryType],
        [IDL.Vec(FinanceEntry)],
        ['query'],
      ),
    'getFinanceEntry' : IDL.Func([IDL.Text], [FinanceEntry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFinanceEntry' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Int, IDL.Text, EntryType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };