/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EntryType = { 'expense' : null } |
  { 'saving' : null } |
  { 'income' : null };
export interface FinanceEntry {
  'id' : string,
  'entryType' : EntryType,
  'owner' : Principal,
  'date' : bigint,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFinanceEntry' : ActorMethod<
    [string, number, bigint, string, EntryType, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFinanceEntry' : ActorMethod<[string], undefined>,
  'getAllFinanceEntries' : ActorMethod<[], Array<FinanceEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntriesByDateRange' : ActorMethod<[bigint, bigint], Array<FinanceEntry>>,
  'getEntriesByType' : ActorMethod<[EntryType], Array<FinanceEntry>>,
  'getFinanceEntry' : ActorMethod<[string], FinanceEntry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFinanceEntry' : ActorMethod<
    [string, number, bigint, string, EntryType, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];